#settings

spring:
  datasource:
    url: jdbc:h2:mem:mydb #conn. string
    username: dan
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /api